let products = [
    {
        id: 1001,
        title: "Cat food 5kg bag",
        description: "A 5kg bag of <em>irresistible </em>" + "organic goodness for your Cat",
        price: 200,
        image: "images/catFood.png",
        availableInventory: 10,
        rating: 4,         
    },
    {
        id: 1002,
        title: "Dog food 5kg bag",
        description: "A 10kg bag of <em>irresistible </em>" + "organic goodness for your Dog",
        price: 250,
        image: "images/dogFood.png",
        availableInventory: 8,
        rating: 3,         
    },
    {
        id: 1003,
        title: "Bird food 5kg bag",
        description: "A 2kg bag of <em>irresistible </em>" + "organic goodness for your Bird",
        price: 100,
        image: "images/birdFood.png",
        availableInventory: 0,
        rating: 5,         
    },
    {
        id: 1004,
        title: "Fish food 5kg bag",
        description: "A 1kg bag of <em>irresistible </em>" + "organic goodness for your Fish",
        price: 50,
        image: "images/fishFood.png",
        availableInventory: 15,
        rating: 3,         
    },
    {
        id: 1005,
        title: "Ferret food 5kg bag",
        description: "A 3kg bag of <em>irresistible </em>" + "organic goodness for your Ferret",
        price: 150,
        image: "images/ferretFood.png",
        availableInventory: 3,
        rating: 4,         
    },
]